/*---------------------------------------------------------------------------*
 *  smthttp.d - LIBERO dialog data definitions for smthttp.c.                *
 *  Generated by LIBERO 2.30 on 25 Nov, 1999, 16:29.                         *
 *  Schema file used: smtschm.c.                                             *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define _LR_NULL_STATE                  -1
#define terminate_event                 -1
#define bad_request_event               0
#define binary_event                    1
#define cancel_event                    2
#define cgi_event                       3
#define client_event                    4
#define close_event                     5
#define directory_event                 6
#define error_event                     7
#define exception_event                 8
#define executable_event                9
#define fatal_event                     10
#define file_event                      11
#define filter_event                    12
#define finished_event                  13
#define forbidden_event                 14
#define get_request_event               15
#define html_event                      16
#define imap_event                      17
#define internal_error_event            18
#define kill_event                      19
#define master_event                    20
#define more_event                      21
#define multi_event                     22
#define multibin_event                  23
#define new_ssl_client_event            24
#define not_found_event                 25
#define not_implemented_event           26
#define ok_event                        27
#define overloaded_event                28
#define post_event                      29
#define post_request_event              30
#define redirect_event                  31
#define restart_event                   32
#define send_header_event               33
#define shutdown_event                  34
#define sock_closed_event               35
#define sock_error_event                36
#define sock_retry_event                37
#define sock_timeout_event              38
#define ssl_error_event                 39
#define timer_event                     40
#define too_large_event                 41
#define unauthorized_event              42
#define update_request_event            43
#define wsx_event                       44
#define wsx_cancel_event                45
#define wsx_install_event               46
#define _LR_STATE_after_init            0
#define _LR_STATE_master_input          1
#define _LR_STATE_master_restart        2
#define _LR_STATE_client                3
#define _LR_STATE_client_input          4
#define _LR_STATE_have_client_request   5
#define _LR_STATE_client_input_post     6
#define _LR_STATE_have_client_post      7
#define _LR_STATE_execute_http_request  8
#define _LR_STATE_process_http_get      9
#define _LR_STATE_have_type_of_get      10
#define _LR_STATE_trying_to_get_file    11
#define _LR_STATE_process_http_post     12
#define _LR_STATE_process_http_update   13
#define _LR_STATE_have_type_of_update   14
#define _LR_STATE_trying_to_update      15
#define _LR_STATE_after_sending_file    16
#define _LR_STATE_trying_to_get_dir     17
#define _LR_STATE_have_default          18
#define _LR_STATE_have_type_of_cgi      19
#define _LR_STATE_before_running_cgi    20
#define _LR_STATE_wait_for_cgi          21
#define _LR_STATE_have_type_of_filter   22
#define _LR_STATE_trying_to_get_filter  23
#define _LR_STATE_wait_for_filter       24
#define _LR_STATE_trying_to_get_wsx     25
#define _LR_STATE_wait_for_wsx          26
#define _LR_STATE_process_wsx_done      27
#define _LR_STATE_process_wsx_multipart 28
#define _LR_STATE_process_wsx_restart   29
#define _LR_STATE_process_wsx_kill      30
#define _LR_STATE_request_finished      31
#define _LR_STATE_defaults              32
#define _LR_STATE_end_thread            33
#define _LR_defaults_state              32


/*- Function prototypes and macros ------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

MODULE initialise_the_thread        (THREAD *thread);
MODULE open_server_log_file         (THREAD *thread);
MODULE load_virtual_hosts           (THREAD *thread);
MODULE check_rootdir_exists         (THREAD *thread);
MODULE open_ssl_socket_if_needed    (THREAD *thread);
MODULE open_master_socket           (THREAD *thread);
MODULE set_server_process_state     (THREAD *thread);
MODULE wait_for_socket_input        (THREAD *thread);
MODULE prepare_client_thread        (THREAD *thread);
MODULE prepare_to_read_request      (THREAD *thread);
MODULE read_input_from_socket       (THREAD *thread);
MODULE accept_client_connection     (THREAD *thread);
MODULE create_ssl_child_thread      (THREAD *thread);
MODULE reload_config_if_needed      (THREAD *thread);
MODULE free_all_server_resources    (THREAD *thread);
MODULE kill_all_active_connections  (THREAD *thread);
MODULE wait_for_connections_to_close (THREAD *thread);
MODULE signal_socket_closed         (THREAD *thread);
MODULE check_socket_type            (THREAD *thread);
MODULE install_wsx_alias            (THREAD *thread);
MODULE cancel_wsx_alias             (THREAD *thread);
MODULE restart_ftp_server_if_reqd   (THREAD *thread);
MODULE restart_ssl_agent_if_reqd    (THREAD *thread);
MODULE reject_client_connection     (THREAD *thread);
MODULE signal_socket_error          (THREAD *thread);
MODULE terminate_the_thread         (THREAD *thread);
MODULE write_http_header            (THREAD *thread);
MODULE signal_bad_request           (THREAD *thread);
MODULE signal_url_unauthorized      (THREAD *thread);
MODULE signal_url_forbidden         (THREAD *thread);
MODULE signal_url_not_found         (THREAD *thread);
MODULE signal_too_large             (THREAD *thread);
MODULE signal_internal_error        (THREAD *thread);
MODULE signal_not_implemented       (THREAD *thread);
MODULE signal_overloaded            (THREAD *thread);
MODULE read_http_request_next       (THREAD *thread);
MODULE check_if_request_complete    (THREAD *thread);
MODULE check_if_post_data_complete  (THREAD *thread);
MODULE parse_http_request           (THREAD *thread);
MODULE resolve_virtual_hostname     (THREAD *thread);
MODULE check_client_ip_allowed      (THREAD *thread);
MODULE read_http_posted_data        (THREAD *thread);
MODULE get_url_type                 (THREAD *thread);
MODULE check_file_or_directory      (THREAD *thread);
MODULE get_url_from_map             (THREAD *thread);
MODULE check_if_keep_alive          (THREAD *thread);
MODULE check_if_protected           (THREAD *thread);
MODULE check_if_send_file           (THREAD *thread);
MODULE send_file_to_browser         (THREAD *thread);
MODULE update_resource_from_request (THREAD *thread);
MODULE get_default_web_page         (THREAD *thread);
MODULE make_directory_listing       (THREAD *thread);
MODULE create_cgi_process           (THREAD *thread);
MODULE wait_process_end             (THREAD *thread);
MODULE close_child_process          (THREAD *thread);
MODULE reparse_process_output       (THREAD *thread);
MODULE create_filter_process        (THREAD *thread);
MODULE pass_request_to_wsx_agent    (THREAD *thread);
MODULE get_wsx_return_fields        (THREAD *thread);
MODULE get_wsx_bin_return_fields    (THREAD *thread);
MODULE get_wsx_error_fields         (THREAD *thread);
MODULE get_wsx_redirect_fields      (THREAD *thread);
MODULE reparse_http_body            (THREAD *thread);
MODULE write_http_body              (THREAD *thread);
MODULE send_master_thread_restart   (THREAD *thread);
MODULE send_master_thread_shutdown  (THREAD *thread);
MODULE partial_clear_http_context   (THREAD *thread);
MODULE signal_closing_server        (THREAD *thread);
MODULE shutdown_the_application     (THREAD *thread);
MODULE flush_socket_requests        (THREAD *thread);

#define the_next_event              _the_next_event
#define the_exception_event         _the_exception_event
#define the_external_event          _the_external_event
#define exception_raised            _exception_raised
#define io_completed                _io_completed


/*- Static areas shared by all threads --------------------------------------*/

static word _LR_nextst [34][47] =
{
    { 0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
    },
    { 0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
     ,0,0,2,0,0,33,0,1,0,0,1,0,0,0,0,1,1
    },
    { 0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,2,0,0
     ,0,0,2,0,0,33,0,2,0,0,1,0,0,0,0,2,2
    },
    { 3,0,0,0,0,0,0,3,0,0,0,0,0,0,3,0,0,0,3,0,0,0,0,0,0,3,3,0,3,0
     ,0,0,0,0,0,3,3,3,3,3,0,3,3,0,0,0,0
    },
    { 4,0,0,0,0,0,0,4,0,0,0,0,0,0,4,0,0,0,4,0,0,0,0,0,0,4,4,5,4,0
     ,0,0,0,0,0,4,4,4,4,4,0,4,4,0,0,0,0
    },
    { 5,0,0,0,0,0,0,5,0,0,0,0,0,8,5,0,0,0,5,0,0,4,0,0,0,5,5,0,5,7
     ,0,0,0,0,0,5,5,5,5,5,0,5,5,0,0,0,0
    },
    { 6,0,0,0,0,0,0,6,0,0,0,0,0,0,6,0,0,0,6,0,0,0,0,0,0,6,6,7,6,0
     ,0,0,0,0,0,6,6,6,6,6,0,6,6,0,0,0,0
    },
    { 7,0,0,0,0,0,0,7,0,0,0,0,0,8,7,0,0,0,7,0,0,6,0,0,0,7,7,0,7,0
     ,0,0,0,0,0,7,7,7,7,7,0,7,7,0,0,0,0
    },
    { 8,0,0,0,0,0,0,8,0,0,0,0,0,0,8,9,0,0,8,0,0,0,0,0,0,8,8,0,8,0
     ,12,0,0,0,0,8,8,8,8,8,0,8,8,13,0,0,0
    },
    { 9,0,0,19,0,0,0,9,0,0,0,0,22,0,9,0,10,31,9,0,0,0,0,0,0,9,9,0
     ,9,0,0,0,0,0,0,9,9,9,9,9,0,9,9,0,25,0,0
    },
    { 10,0,0,0,0,0,17,10,0,11,0,11,0,0,10,0,0,0,10,0,0,0,0,0,0,10
     ,10,0,10,0,0,0,0,0,0,10,10,10,10,10,0,10,10,0,0,0,0
    },
    { 11,0,0,0,0,0,0,11,0,0,0,0,0,0,11,0,0,0,11,0,0,0,0,0,0,11,11
     ,16,11,0,0,0,0,31,0,11,11,11,11,11,0,11,11,0,0,0,0
    },
    { 12,0,0,19,0,0,0,12,0,0,0,0,22,0,12,0,12,12,12,0,0,0,0,0,0,12
     ,12,0,12,0,0,0,0,0,0,12,12,12,12,12,0,12,12,0,25,0,0
    },
    { 13,0,0,13,0,0,0,13,0,0,0,0,13,0,13,0,14,13,13,0,0,0,0,0,0,13
     ,13,0,13,0,0,0,0,0,0,13,13,13,13,13,0,13,13,0,13,0,0
    },
    { 14,0,0,0,0,0,14,14,0,14,0,15,0,0,14,0,0,0,14,0,0,0,0,0,0,15
     ,14,0,14,0,0,0,0,0,0,14,14,14,14,14,0,14,14,0,0,0,0
    },
    { 15,0,0,0,0,0,0,15,0,0,0,0,0,0,15,0,0,0,15,0,0,0,0,0,0,15,15
     ,31,15,0,0,0,0,0,0,15,15,15,15,15,0,15,15,0,0,0,0
    },
    { 16,0,0,0,0,0,0,16,0,0,0,0,0,31,16,0,0,0,16,0,0,0,0,0,0,16,16
     ,0,16,0,0,0,0,0,0,16,16,16,16,16,0,16,16,0,0,0,0
    },
    { 17,0,0,0,0,0,0,17,0,0,0,0,0,0,17,0,0,0,17,0,0,0,0,0,0,17,17
     ,18,17,0,0,0,0,0,0,17,17,17,17,17,0,17,17,0,0,0,0
    },
    { 18,0,0,0,0,0,0,18,0,0,0,9,0,0,18,0,0,0,18,0,0,0,0,0,0,16,18
     ,0,18,0,0,0,0,31,0,18,18,18,18,18,0,18,18,0,0,0,0
    },
    { 19,0,0,0,0,0,17,19,0,20,0,11,0,0,19,0,0,0,19,0,0,0,0,0,0,19
     ,19,0,19,0,0,0,0,0,0,19,19,19,19,19,0,19,19,0,0,0,0
    },
    { 20,0,0,0,0,0,0,20,0,0,0,0,0,0,20,0,0,0,20,0,0,0,0,0,0,20,20
     ,21,20,0,0,0,0,0,0,20,20,20,20,20,0,20,20,0,0,0,0
    },
    { 21,0,0,0,0,0,0,21,0,0,0,0,0,16,21,0,0,0,21,0,0,0,0,0,0,21,21
     ,0,21,0,0,9,0,0,0,21,21,21,21,21,21,21,21,0,0,0,0
    },
    { 22,0,0,0,0,0,17,22,0,23,0,23,0,0,22,0,0,0,22,0,0,0,0,0,0,22
     ,22,0,22,0,0,0,0,0,0,22,22,22,22,22,0,22,22,0,0,0,0
    },
    { 23,0,0,0,0,0,0,23,0,0,0,0,0,0,23,0,0,0,23,0,0,0,0,0,0,23,23
     ,24,23,0,0,0,0,0,0,23,23,23,23,23,0,23,23,0,0,0,0
    },
    { 24,0,0,0,0,0,0,24,0,0,0,0,0,16,24,0,0,0,24,0,0,0,0,0,0,24,24
     ,0,24,0,0,9,0,0,0,24,24,24,24,24,24,24,24,0,0,0,0
    },
    { 25,0,0,0,0,0,0,25,0,0,0,0,0,0,25,0,0,0,25,0,0,0,0,0,0,25,25
     ,26,25,0,0,0,0,0,0,25,25,25,25,25,0,25,25,0,0,0,0
    },
    { 26,27,0,0,0,0,0,26,0,0,0,0,0,0,26,0,0,0,26,30,0,0,28,28,0,26
     ,26,27,26,0,0,26,29,0,0,26,26,26,26,26,0,26,26,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,0,0
     ,0,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,0
     ,0,26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29,0,0
     ,0,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,0,0
     ,0,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 31,0,0,0,0,31,0,31,0,0,0,0,0,0,31,0,0,0,31,0,0,0,0,0,0,31,31
     ,4,31,0,0,0,0,0,0,31,31,31,31,31,0,31,31,0,0,0,0
    },
    { 32,32,33,32,32,32,32,32,33,32,32,32,32,32,32,32,32,32,32,32
     ,32,32,32,32,32,32,32,32,32,32,32,32,32,32,33,33,33,33,33,32
     ,32,32,32,32,32,32,32
    },
    { 0,0,0,0,33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    }
};

static word _LR_action [34][47] =
{
    { 0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
    },
    { 0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,4,0,0
     ,0,0,7,0,0,9,0,8,0,0,6,0,0,0,0,12,11
    },
    { 0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,14,0
     ,0,0,0,7,0,0,9,0,8,0,0,13,0,0,0,0,12,11
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,26,25,0,0,0,0,0,0,16,15,27,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,29,20,0,0,0,23,0,0,27,0,0,0,21
     ,24,0,25,28,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,30,25,0,0,0,0,0,0,16,15,27,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,29,20,0,0,0,23,0,0,27,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,31,0,0,23,0,0,0,0,0,0,21,24
     ,0,25,0,31,0,0,0,0,16,15,16,16,16,0,22,19,31,0,0,0
    },
    { 18,0,0,32,0,0,0,17,0,0,0,0,32,0,20,0,32,33,23,0,0,0,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,34,0,0
    },
    { 18,0,0,0,0,0,34,17,0,34,0,34,0,0,20,0,0,0,23,0,0,0,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,35,25,0,0,0,0,36,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,32,0,0,0,17,0,0,0,0,32,0,20,0,18,18,23,0,0,0,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,34,0,0
    },
    { 18,0,0,18,0,0,0,17,0,0,0,0,18,0,20,0,32,18,23,0,0,0,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,18,0,0
    },
    { 18,0,0,0,0,0,20,17,0,20,0,34,0,0,20,0,0,0,23,0,0,0,0,0,0,34
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,37,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,38,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,39,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,31,0,0,20,0,0,0,23,0,0,0,0,0,0,40,24
     ,0,25,0,0,0,0,36,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,34,17,0,34,0,34,0,0,20,0,0,0,23,0,0,0,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,41,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,44,0,0,0,0,0,43,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,0,25,0,0,31,0,0,0,16,15,16,16,16,42,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,34,17,0,34,0,34,0,0,20,0,0,0,23,0,0,0,0,0,0,21
     ,24,0,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,45,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,44,0,0,0,0,0,43,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,0,25,0,0,31,0,0,0,16,15,16,16,16,42,22,19,0,0,0,0
    },
    { 18,0,0,0,0,0,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,46,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 18,48,0,0,0,0,0,49,0,0,0,0,0,0,20,0,0,0,23,47,0,0,47,48,0,21
     ,24,47,25,0,0,50,47,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,0,0
     ,0,52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,53,0,0
     ,0,52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,54,0,0
     ,0,55,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,56,0,0
     ,0,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 18,0,0,0,0,16,0,17,0,0,0,0,0,0,20,0,0,0,23,0,0,0,0,0,0,21,24
     ,58,25,0,0,0,0,0,0,16,15,16,16,16,0,22,19,0,0,0,0
    },
    { 10,10,59,10,10,10,10,10,59,10,60,10,10,10,10,10,10,10,10,10
     ,10,10,10,10,10,10,10,10,10,10,10,10,10,10,59,59,61,59,59,10
     ,10,10,10,10,10,10,10
    },
    { 0,0,0,0,62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    }
};

static word _LR_offset [] =
{
    0,
    0,
    8,
    12,
    16,
    19,
    21,
    23,
    27,
    30,
    33,
    34,
    36,
    38,
    46,
    49,
    52,
    54,
    57,
    60,
    63,
    66,
    69,
    72,
    75,
    78,
    81,
    84,
    86,
    88,
    92,
    95,
    97,
    99,
    103,
    105,
    109,
    112,
    116,
    118,
    120,
    124,
    127,
    129,
    134,
    138,
    141,
    143,
    145,
    147,
    151,
    155,
    160,
    164,
    168,
    174,
    180,
    186,
    192,
    195,
    197,
    202,
    205
};

static word _LR_vector [] =
{
    0,1,2,3,4,5,6,_LR_STOP,
    4,5,6,_LR_STOP,
    7,8,9,_LR_STOP,
    10,6,_LR_STOP,
    11,_LR_STOP,
    12,_LR_STOP,
    13,14,15,_LR_STOP,
    4,6,_LR_STOP,
    16,17,_LR_STOP,
    _LR_STOP,
    18,_LR_STOP,
    19,_LR_STOP,
    0,1,2,20,21,3,6,_LR_STOP,
    22,6,_LR_STOP,
    23,24,_LR_STOP,
    24,_LR_STOP,
    25,24,_LR_STOP,
    26,24,_LR_STOP,
    27,24,_LR_STOP,
    28,24,_LR_STOP,
    29,24,_LR_STOP,
    30,24,_LR_STOP,
    31,24,_LR_STOP,
    32,24,_LR_STOP,
    33,24,_LR_STOP,
    34,35,_LR_STOP,
    9,_LR_STOP,
    36,_LR_STOP,
    37,38,39,_LR_STOP,
    40,36,_LR_STOP,
    41,_LR_STOP,
    42,_LR_STOP,
    43,25,44,_LR_STOP,
    45,_LR_STOP,
    46,25,47,_LR_STOP,
    25,44,_LR_STOP,
    48,25,44,_LR_STOP,
    44,_LR_STOP,
    49,_LR_STOP,
    50,25,47,_LR_STOP,
    51,52,_LR_STOP,
    52,_LR_STOP,
    53,54,25,47,_LR_STOP,
    53,25,24,_LR_STOP,
    55,52,_LR_STOP,
    56,_LR_STOP,
    57,_LR_STOP,
    58,_LR_STOP,
    59,25,24,_LR_STOP,
    60,25,24,_LR_STOP,
    61,25,62,44,_LR_STOP,
    54,25,47,_LR_STOP,
    61,25,62,_LR_STOP,
    61,25,62,63,24,_LR_STOP,
    54,25,47,63,24,_LR_STOP,
    61,25,62,64,24,_LR_STOP,
    54,25,47,64,24,_LR_STOP,
    65,9,_LR_STOP,
    17,_LR_STOP,
    66,13,67,24,_LR_STOP,
    23,17,_LR_STOP,
    68,24,_LR_STOP
};

static HOOK *_LR_module [69] = {
    open_server_log_file,
    load_virtual_hosts,
    check_rootdir_exists,
    open_ssl_socket_if_needed,
    open_master_socket,
    set_server_process_state,
    wait_for_socket_input,
    prepare_client_thread,
    prepare_to_read_request,
    read_input_from_socket,
    accept_client_connection,
    create_ssl_child_thread,
    reload_config_if_needed,
    free_all_server_resources,
    kill_all_active_connections,
    wait_for_connections_to_close,
    signal_socket_closed,
    check_socket_type,
    install_wsx_alias,
    cancel_wsx_alias,
    restart_ftp_server_if_reqd,
    restart_ssl_agent_if_reqd,
    reject_client_connection,
    signal_socket_error,
    terminate_the_thread,
    write_http_header,
    signal_bad_request,
    signal_url_unauthorized,
    signal_url_forbidden,
    signal_url_not_found,
    signal_too_large,
    signal_internal_error,
    signal_not_implemented,
    signal_overloaded,
    read_http_request_next,
    check_if_request_complete,
    check_if_post_data_complete,
    parse_http_request,
    resolve_virtual_hostname,
    check_client_ip_allowed,
    read_http_posted_data,
    get_url_type,
    check_file_or_directory,
    get_url_from_map,
    check_if_keep_alive,
    check_if_protected,
    check_if_send_file,
    send_file_to_browser,
    update_resource_from_request,
    get_default_web_page,
    make_directory_listing,
    create_cgi_process,
    wait_process_end,
    close_child_process,
    reparse_process_output,
    create_filter_process,
    pass_request_to_wsx_agent,
    get_wsx_return_fields,
    get_wsx_bin_return_fields,
    get_wsx_error_fields,
    get_wsx_redirect_fields,
    reparse_http_body,
    write_http_body,
    send_master_thread_restart,
    send_master_thread_shutdown,
    partial_clear_http_context,
    signal_closing_server,
    shutdown_the_application,
    flush_socket_requests
};

#if (defined (DEBUG))
static char *_LR_mname [69] =
{
     "Open-Server-Log-File",
     "Load-Virtual-Hosts",
     "Check-Rootdir-Exists",
     "Open-Ssl-Socket-If-Needed",
     "Open-Master-Socket",
     "Set-Server-Process-State",
     "Wait-For-Socket-Input",
     "Prepare-Client-Thread",
     "Prepare-To-Read-Request",
     "Read-Input-From-Socket",
     "Accept-Client-Connection",
     "Create-Ssl-Child-Thread",
     "Reload-Config-If-Needed",
     "Free-All-Server-Resources",
     "Kill-All-Active-Connections",
     "Wait-For-Connections-To-Close",
     "Signal-Socket-Closed",
     "Check-Socket-Type",
     "Install-Wsx-Alias",
     "Cancel-Wsx-Alias",
     "Restart-Ftp-Server-If-Reqd",
     "Restart-Ssl-Agent-If-Reqd",
     "Reject-Client-Connection",
     "Signal-Socket-Error",
     "Terminate-The-Thread",
     "Write-Http-Header",
     "Signal-Bad-Request",
     "Signal-Url-Unauthorized",
     "Signal-Url-Forbidden",
     "Signal-Url-Not-Found",
     "Signal-Too-Large",
     "Signal-Internal-Error",
     "Signal-Not-Implemented",
     "Signal-Overloaded",
     "Read-Http-Request-Next",
     "Check-If-Request-Complete",
     "Check-If-Post-Data-Complete",
     "Parse-Http-Request",
     "Resolve-Virtual-Hostname",
     "Check-Client-Ip-Allowed",
     "Read-Http-Posted-Data",
     "Get-Url-Type",
     "Check-File-Or-Directory",
     "Get-Url-From-Map",
     "Check-If-Keep-Alive",
     "Check-If-Protected",
     "Check-If-Send-File",
     "Send-File-To-Browser",
     "Update-Resource-From-Request",
     "Get-Default-Web-Page",
     "Make-Directory-Listing",
     "Create-Cgi-Process",
     "Wait-Process-End",
     "Close-Child-Process",
     "Reparse-Process-Output",
     "Create-Filter-Process",
     "Pass-Request-To-Wsx-Agent",
     "Get-Wsx-Return-Fields",
     "Get-Wsx-Bin-Return-Fields",
     "Get-Wsx-Error-Fields",
     "Get-Wsx-Redirect-Fields",
     "Reparse-Http-Body",
     "Write-Http-Body",
     "Send-Master-Thread-Restart",
     "Send-Master-Thread-Shutdown",
     "Partial-Clear-Http-Context",
     "Signal-Closing-Server",
     "Shutdown-The-Application",
     "Flush-Socket-Requests"
};

static char *_LR_sname [34] =
{
     "After-Init",
     "Master-Input",
     "Master-Restart",
     "Client",
     "Client-Input",
     "Have-Client-Request",
     "Client-Input-Post",
     "Have-Client-Post",
     "Execute-Http-Request",
     "Process-Http-Get",
     "Have-Type-Of-Get",
     "Trying-To-Get-File",
     "Process-Http-Post",
     "Process-Http-Update",
     "Have-Type-Of-Update",
     "Trying-To-Update",
     "After-Sending-File",
     "Trying-To-Get-Dir",
     "Have-Default",
     "Have-Type-Of-Cgi",
     "Before-Running-Cgi",
     "Wait-For-Cgi",
     "Have-Type-Of-Filter",
     "Trying-To-Get-Filter",
     "Wait-For-Filter",
     "Trying-To-Get-Wsx",
     "Wait-For-Wsx",
     "Process-Wsx-Done",
     "Process-Wsx-Multipart",
     "Process-Wsx-Restart",
     "Process-Wsx-Kill",
     "Request-Finished",
     "Defaults",
     "End-Thread"
};

static char *_LR_ename [47] =
{
     "Bad-Request-Event",
     "Binary-Event",
     "Cancel-Event",
     "Cgi-Event",
     "Client-Event",
     "Close-Event",
     "Directory-Event",
     "Error-Event",
     "Exception-Event",
     "Executable-Event",
     "Fatal-Event",
     "File-Event",
     "Filter-Event",
     "Finished-Event",
     "Forbidden-Event",
     "Get-Request-Event",
     "Html-Event",
     "Imap-Event",
     "Internal-Error-Event",
     "Kill-Event",
     "Master-Event",
     "More-Event",
     "Multi-Event",
     "Multibin-Event",
     "New-Ssl-Client-Event",
     "Not-Found-Event",
     "Not-Implemented-Event",
     "Ok-Event",
     "Overloaded-Event",
     "Post-Event",
     "Post-Request-Event",
     "Redirect-Event",
     "Restart-Event",
     "Send-Header-Event",
     "Shutdown-Event",
     "Sock-Closed-Event",
     "Sock-Error-Event",
     "Sock-Retry-Event",
     "Sock-Timeout-Event",
     "Ssl-Error-Event",
     "Timer-Event",
     "Too-Large-Event",
     "Unauthorized-Event",
     "Update-Request-Event",
     "Wsx-Event",
     "Wsx-Cancel-Event",
     "Wsx-Install-Event"
};
#else
static char *_LR_mname [69] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33",
     "34",
     "35",
     "36",
     "37",
     "38",
     "39",
     "40",
     "41",
     "42",
     "43",
     "44",
     "45",
     "46",
     "47",
     "48",
     "49",
     "50",
     "51",
     "52",
     "53",
     "54",
     "55",
     "56",
     "57",
     "58",
     "59",
     "60",
     "61",
     "62",
     "63",
     "64",
     "65",
     "66",
     "67",
     "68"
};

static char *_LR_sname [34] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33"
};

static char *_LR_ename [47] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33",
     "34",
     "35",
     "36",
     "37",
     "38",
     "39",
     "40",
     "41",
     "42",
     "43",
     "44",
     "45",
     "46"
};
#endif
