/*---------------------------------------------------------------------------*
 *  smtsimu.d - LIBERO dialog data definitions for smtsimu.c.                *
 *  Generated by LIBERO 2.30 on 22 Dec, 1998, 15:35.                         *
 *  Schema file used: smtschm.c.                                             *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define _LR_NULL_STATE                  -1
#define terminate_event                 -1
#define alarm_event                     0
#define error_event                     1
#define ok_event                        2
#define shutdown_event                  3
#define _LR_STATE_after_init            0
#define _LR_STATE_getting_event         1
#define _LR_STATE_defaults              2
#define _LR_defaults_state              2


/*- Function prototypes and macros ------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

MODULE initialise_the_thread        (THREAD *thread);
MODULE get_next_event_from_queue    (THREAD *thread);
MODULE make_socket_call             (THREAD *thread);
MODULE terminate_the_thread         (THREAD *thread);

#define the_next_event              _the_next_event
#define the_exception_event         _the_exception_event
#define the_external_event          _the_external_event
#define exception_raised            _exception_raised
#define io_completed                _io_completed


/*- Static areas shared by all threads --------------------------------------*/

static word _LR_nextst [3][4] =
{
    { 0,0,1,0 },
    { 1,0,0,0 },
    { 0,0,0,2 }
};

static word _LR_action [3][4] =
{
    { 0,2,1,0 },
    { 3,0,0,0 },
    { 0,0,0,2 }
};

static word _LR_offset [] =
{
    0,
    0,
    1,
    3
};

static word _LR_vector [] =
{
    _LR_STOP,
    2,_LR_STOP,
    1,0,_LR_STOP
};

static HOOK *_LR_module [3] = {
    get_next_event_from_queue,
    make_socket_call,
    terminate_the_thread
};

#if (defined (DEBUG))
static char *_LR_mname [3] =
{
     "Get-Next-Event-From-Queue",
     "Make-Socket-Call",
     "Terminate-The-Thread"
};

static char *_LR_sname [3] =
{
     "After-Init",
     "Getting-Event",
     "Defaults"
};

static char *_LR_ename [4] =
{
     "Alarm-Event",
     "Error-Event",
     "Ok-Event",
     "Shutdown-Event"
};
#else
static char *_LR_mname [3] =
{
     "0",
     "1",
     "2"
};

static char *_LR_sname [3] =
{
     "0",
     "1",
     "2"
};

static char *_LR_ename [4] =
{
     "0",
     "1",
     "2",
     "3"
};
#endif
