/*---------------------------------------------------------------------------*
 *  xiadmin.d - LIBERO dialog data definitions for xiadmin.c.                *
 *  Generated by LIBERO 2.30 on 25 May, 1999, 15:08.                         *
 *  Schema file used: smtschm.c.                                             *
 *---------------------------------------------------------------------------*/

/*- Symbolic constants and event numbers ------------------------------------*/

#define _LR_STOP                        0xFFFFL
#define _LR_NULL_EVENT                  -2
#define _LR_NULL_STATE                  -1
#define terminate_event                 -1
#define aliases_event                   0
#define back_event                      1
#define basehost_event                  2
#define cgi_event                       3
#define clear_event                     4
#define config_event                    5
#define console_event                   6
#define data_error_event                7
#define default_event                   8
#define define_event                    9
#define define_aliases_event            10
#define define_dirs_event               11
#define define_environ_event            12
#define define_users_event              13
#define delete_event                    14
#define details_event                   15
#define enter_event                     16
#define errors_event                    17
#define exception_event                 18
#define exit_event                      19
#define filters_event                   20
#define first_event                     21
#define ftp_event                       22
#define halt_event                      23
#define help_event                      24
#define hosts_event                     25
#define invert_event                    26
#define logging_event                   27
#define main_event                      28
#define messages_event                  29
#define mimes_event                     30
#define new_event                       31
#define new_session_event               32
#define next_event                      33
#define ok_event                        34
#define refresh_event                   35
#define reshow_form_event               36
#define resource_event                  37
#define restart_event                   38
#define return_event                    39
#define save_event                      40
#define security_event                  41
#define select_config_event             42
#define select_resource_event           43
#define select_user_event               44
#define server_event                    45
#define shutdown_event                  46
#define test_event                      47
#define timeout_event                   48
#define undo_event                      49
#define vhosts_event                    50
#define wizard_event                    51
#define wsx_event                       52
#define _LR_STATE_after_init            0
#define _LR_STATE_start_session         1
#define _LR_STATE_select_initial        2
#define _LR_STATE_main_menu             3
#define _LR_STATE_config_list           4
#define _LR_STATE_config_server         5
#define _LR_STATE_config_value_list     6
#define _LR_STATE_config_server_list    7
#define _LR_STATE_config_errors         8
#define _LR_STATE_config_cgi            9
#define _LR_STATE_config_cgi_sub_list   10
#define _LR_STATE_config_ftp            11
#define _LR_STATE_config_ftp_users      12
#define _LR_STATE_config_ftp_user       13
#define _LR_STATE_config_ftp_dirs       14
#define _LR_STATE_config_ftp_user_list  15
#define _LR_STATE_config_ftp_sub_list   16
#define _LR_STATE_config_security       17
#define _LR_STATE_config_resources      18
#define _LR_STATE_config_user_list      19
#define _LR_STATE_config_logging        20
#define _LR_STATE_console_panel         21
#define _LR_STATE_console_messages      22
#define _LR_STATE_console_config        23
#define _LR_STATE_connection_list       24
#define _LR_STATE_vhost_wizard          25
#define _LR_STATE_defaults              26
#define _LR_defaults_state              26


/*- Function prototypes and macros ------------------------------------------*/

#ifndef MODULE
#define MODULE  static void             /*  Libero dialog modules            */
#endif

MODULE initialise_the_thread        (THREAD *thread);
MODULE determine_initial_screen     (THREAD *thread);
MODULE open_main_admin_menu         (THREAD *thread);
MODULE show_main_admin_menu         (THREAD *thread);
MODULE decode_http_request_reponse  (THREAD *thread);
MODULE use_defaults_config_name     (THREAD *thread);
MODULE load_current_config_file     (THREAD *thread);
MODULE open_config_server           (THREAD *thread);
MODULE show_config_server           (THREAD *thread);
MODULE dialog_call                  (THREAD *thread);
MODULE open_config_list             (THREAD *thread);
MODULE show_config_list_first       (THREAD *thread);
MODULE close_all_forms              (THREAD *thread);
MODULE open_vhost_wizard            (THREAD *thread);
MODULE show_vhost_wizard            (THREAD *thread);
MODULE check_config_list_livelink   (THREAD *thread);
MODULE close_current_form           (THREAD *thread);
MODULE dialog_return                (THREAD *thread);
MODULE show_config_list_next        (THREAD *thread);
MODULE use_basehost_config_name     (THREAD *thread);
MODULE cancel_current_config_file   (THREAD *thread);
MODULE update_config_server         (THREAD *thread);
MODULE save_current_config_file     (THREAD *thread);
MODULE show_config_server_defaults  (THREAD *thread);
MODULE open_config_aliases          (THREAD *thread);
MODULE show_config_value_list_first (THREAD *thread);
MODULE open_config_vhosts           (THREAD *thread);
MODULE open_config_cgi              (THREAD *thread);
MODULE show_config_cgi              (THREAD *thread);
MODULE open_config_ftp              (THREAD *thread);
MODULE show_config_ftp              (THREAD *thread);
MODULE open_config_security         (THREAD *thread);
MODULE show_config_security         (THREAD *thread);
MODULE open_config_logging          (THREAD *thread);
MODULE show_config_logging          (THREAD *thread);
MODULE open_config_mimes            (THREAD *thread);
MODULE open_config_errors           (THREAD *thread);
MODULE show_config_errors           (THREAD *thread);
MODULE open_config_wsx              (THREAD *thread);
MODULE open_config_filter           (THREAD *thread);
MODULE test_url_mapping             (THREAD *thread);
MODULE reshow_current_form          (THREAD *thread);
MODULE validate_config_value_list   (THREAD *thread);
MODULE update_config_value_list     (THREAD *thread);
MODULE clear_config_value_list      (THREAD *thread);
MODULE show_config_value_list_next  (THREAD *thread);
MODULE update_config_errors         (THREAD *thread);
MODULE show_config_errors_defaults  (THREAD *thread);
MODULE update_config_cgi            (THREAD *thread);
MODULE show_config_cgi_defaults     (THREAD *thread);
MODULE open_config_cgi_envir        (THREAD *thread);
MODULE open_config_cgi_alias        (THREAD *thread);
MODULE update_config_ftp            (THREAD *thread);
MODULE show_config_ftp_defaults     (THREAD *thread);
MODULE open_config_ftp_users        (THREAD *thread);
MODULE show_config_ftp_users_first  (THREAD *thread);
MODULE open_config_ftp_dirs         (THREAD *thread);
MODULE show_config_ftp_dirs_first   (THREAD *thread);
MODULE open_config_ftp_alias        (THREAD *thread);
MODULE check_ftp_users_livelink     (THREAD *thread);
MODULE open_config_ftp_user         (THREAD *thread);
MODULE show_config_ftp_user_new     (THREAD *thread);
MODULE cancel_config_resource_file  (THREAD *thread);
MODULE save_config_resource_file    (THREAD *thread);
MODULE show_config_ftp_users_next   (THREAD *thread);
MODULE show_config_ftp_users_same   (THREAD *thread);
MODULE show_config_ftp_user         (THREAD *thread);
MODULE update_config_ftp_user       (THREAD *thread);
MODULE delete_config_ftp_user       (THREAD *thread);
MODULE show_config_ftp_user_first   (THREAD *thread);
MODULE show_config_ftp_user_defaults (THREAD *thread);
MODULE set_permissions_as_chosen    (THREAD *thread);
MODULE show_config_ftp_user_next    (THREAD *thread);
MODULE check_ftp_dir_livelink       (THREAD *thread);
MODULE cancel_config_ftp_dir_file   (THREAD *thread);
MODULE save_config_ftp_dir_file     (THREAD *thread);
MODULE show_config_ftp_dirs_next    (THREAD *thread);
MODULE check_new_ftp_dir_name       (THREAD *thread);
MODULE open_config_ftp_user_list    (THREAD *thread);
MODULE show_config_ftp_dirs_same    (THREAD *thread);
MODULE update_config_ftp_user_list  (THREAD *thread);
MODULE update_config_security       (THREAD *thread);
MODULE show_config_security_defaults (THREAD *thread);
MODULE open_config_resources        (THREAD *thread);
MODULE show_config_resources_first  (THREAD *thread);
MODULE check_resources_livelink     (THREAD *thread);
MODULE update_config_resources      (THREAD *thread);
MODULE show_config_resources_next   (THREAD *thread);
MODULE check_new_resource_name      (THREAD *thread);
MODULE open_config_user_list        (THREAD *thread);
MODULE show_config_resources_same   (THREAD *thread);
MODULE update_config_user_list      (THREAD *thread);
MODULE update_config_logging        (THREAD *thread);
MODULE show_config_logging_defaults (THREAD *thread);
MODULE clear_console_panel_statistics (THREAD *thread);
MODULE show_console_panel           (THREAD *thread);
MODULE open_console_config          (THREAD *thread);
MODULE show_console_config          (THREAD *thread);
MODULE open_console_messages        (THREAD *thread);
MODULE show_console_messages        (THREAD *thread);
MODULE open_connection_list         (THREAD *thread);
MODULE show_connection_list         (THREAD *thread);
MODULE clear_console_messages       (THREAD *thread);
MODULE invert_console_data          (THREAD *thread);
MODULE update_console_config        (THREAD *thread);
MODULE reload_server_base_config    (THREAD *thread);
MODULE show_console_config_defaults (THREAD *thread);
MODULE validate_vhost_definition    (THREAD *thread);
MODULE create_vhost_definition      (THREAD *thread);
MODULE send_resource_file_if_known  (THREAD *thread);
MODULE terminate_the_thread         (THREAD *thread);
MODULE check_simple_livelink        (THREAD *thread);
MODULE redirect_to_home_page        (THREAD *thread);
MODULE open_console_panel           (THREAD *thread);
MODULE restart_http_server_agent    (THREAD *thread);
MODULE shutdown_http_server_agent   (THREAD *thread);

#define the_next_event              _the_next_event
#define the_exception_event         _the_exception_event
#define the_external_event          _the_external_event
#define exception_raised            _exception_raised
#define io_completed                _io_completed


/*- Static areas shared by all threads --------------------------------------*/

static word _LR_nextst [27][53] =
{
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,3,0
     ,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,25,0
    },
    { 0,4,5,0,0,0,0,0,5,0,0,0,0,0,0,0,4,0,0,0,0,4,0,0,0,0,0,0,0,0
     ,0,25,0,4,0,0,4,0,0,4,4,0,5,0,0,0,0,0,0,0,0,0,0
    },
    { 6,5,0,9,0,0,0,0,5,0,0,0,0,0,0,0,0,8,0,0,7,0,11,0,0,0,0,20,0
     ,0,6,0,0,0,0,0,0,0,0,0,5,17,0,0,0,0,0,5,0,5,6,0,7
    },
    { 6,6,0,9,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,11,0,0,0,0,20,0
     ,0,6,0,0,6,0,0,0,0,0,0,6,17,0,0,0,5,0,0,0,6,6,0,0
    },
    { 7,5,0,9,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,11,0,0,0,0,20,0
     ,0,7,0,0,7,0,0,0,0,0,0,5,17,0,0,0,5,0,0,0,7,7,0,0
    },
    { 0,5,0,0,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,8,0,0,0
    },
    { 6,9,0,0,0,0,0,0,9,0,10,0,10,0,0,0,0,0,0,0,0,0,11,0,0,0,0,20
     ,0,0,6,0,0,0,0,0,0,0,0,0,9,17,0,0,0,5,0,0,0,9,6,0,0
    },
    { 10,9,0,9,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,11,0,0,0,0,20
     ,0,0,10,0,0,10,0,0,0,0,0,0,9,17,0,0,0,5,0,0,0,10,10,0,0
    },
    { 6,11,0,9,0,0,0,0,11,0,16,14,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,20,0,0,6,0,0,0,0,0,0,0,0,0,11,17,0,0,0,5,0,0,0,11,6,0,0
    },
    { 12,11,0,9,12,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,12,11,0,0,0,0
     ,20,0,0,12,13,0,12,0,12,0,0,0,0,11,17,0,0,13,5,0,0,0,12,12,0
     ,0
    },
    { 0,12,0,0,0,0,0,0,13,13,0,0,0,0,13,0,0,0,0,0,0,13,0,0,0,0,0,0
     ,0,0,0,13,0,13,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,13,0,0,0
    },
    { 0,11,0,0,0,0,0,0,0,15,0,0,0,0,0,0,14,0,0,0,0,14,0,0,0,0,0,0
     ,0,0,0,0,0,14,0,0,0,0,0,0,11,0,0,15,0,0,0,0,0,0,0,0,0
    },
    { 15,14,0,9,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,11,0,0,0,0
     ,20,0,0,15,0,0,15,0,0,0,0,0,0,14,17,0,0,0,5,0,0,0,15,15,0,0
    },
    { 16,11,0,9,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16,11,0,0,0,0
     ,20,0,0,16,0,0,16,0,0,0,0,0,0,11,17,0,0,0,5,0,0,0,16,16,0,0
    },
    { 6,17,0,9,0,0,0,0,17,18,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,20
     ,0,0,6,0,0,0,0,0,0,0,0,0,17,0,0,0,0,5,0,0,0,17,6,0,0
    },
    { 0,17,0,0,0,0,0,0,0,19,0,0,0,0,0,0,18,0,0,0,0,18,0,0,0,0,0,0
     ,0,0,0,0,0,18,0,0,0,0,0,0,17,0,0,19,0,0,0,0,0,18,0,0,0
    },
    { 19,18,0,9,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19,11,0,0,0,0
     ,20,0,0,19,0,0,19,0,0,0,0,0,0,18,17,0,0,0,5,0,0,0,19,19,0,0
    },
    { 6,20,0,9,0,0,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0
     ,0,6,0,0,0,0,0,0,0,0,0,20,17,0,0,0,5,0,0,0,20,6,0,0
    },
    { 0,3,0,0,21,0,0,0,0,23,0,0,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,22,0,0,0,0,0,21,21,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,21,0,0,22,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0
     ,0,0,0,0,0,0,0,22,22,0,0,22,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,23,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,23,0,0,0
    },
    { 0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,24,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,25,0,0,0,0,0,0,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,21,26,0,0,0,0,0,0,0,0,26,0,26,1,0,0,0,26,26,0,0
     ,0,0,0,0,0,2,0,0,0,26,26,26,0,0,0,0,0,0,0,26,0,26,0,0,0,0
    }
};

static word _LR_action [27][53] =
{
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,3,0
     ,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,7,0
    },
    { 0,9,12,0,0,0,0,0,4,0,0,0,0,0,0,0,8,0,0,0,0,10,0,0,0,0,0,0,0
     ,0,0,7,0,11,0,0,10,0,0,10,9,0,13,0,0,0,0,0,0,0,0,0,0
    },
    { 18,14,0,20,0,0,0,0,16,0,0,0,0,0,0,0,0,25,0,0,27,0,21,0,0,0,0
     ,23,0,0,24,0,0,0,0,0,0,0,0,0,15,22,0,0,0,0,0,28,0,17,19,0,26
    },
    { 35,14,0,37,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,38,0,0,0,0
     ,40,0,0,41,0,0,33,0,0,0,0,0,0,29,39,0,0,0,34,0,0,0,31,36,0,0
    },
    { 35,42,0,37,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,38,0,0,0,0
     ,40,0,0,41,0,0,33,0,0,0,0,0,0,43,39,0,0,0,34,0,0,0,31,36,0,0
    },
    { 0,42,0,0,0,0,0,0,45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,44,0,0,0,0,0,0,0,0,46,0,0,0
    },
    { 51,14,0,0,0,0,0,0,48,0,58,0,57,0,0,0,0,0,0,0,0,0,53,0,0,0,0
     ,55,0,0,56,0,0,0,0,0,0,0,0,0,47,54,0,0,0,50,0,0,0,49,52,0,0
    },
    { 35,59,0,37,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,38,0,0,0,0
     ,40,0,0,41,0,0,33,0,0,0,0,0,0,60,39,0,0,0,34,0,0,0,31,36,0,0
    },
    { 65,14,0,67,0,0,0,0,62,0,73,72,0,71,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,69,0,0,70,0,0,0,0,0,0,0,0,0,61,68,0,0,0,64,0,0,0,63,66,0,0
    },
    { 35,76,0,37,30,0,0,0,0,0,0,0,0,0,0,0,74,0,0,0,0,79,38,0,0,0,0
     ,40,0,0,41,75,0,80,0,81,0,0,0,0,77,39,0,0,82,34,0,0,0,78,36
     ,0,0
    },
    { 0,83,0,0,0,0,0,0,87,90,0,0,0,0,86,0,0,0,0,0,0,89,0,0,0,0,0,0
     ,0,0,0,84,0,91,0,0,0,0,0,0,85,0,0,0,0,0,0,0,0,88,0,0,0
    },
    { 0,93,0,0,0,0,0,0,0,97,0,0,0,0,0,0,92,0,0,0,0,95,0,0,0,0,0,0
     ,0,0,0,0,0,96,0,0,0,0,0,0,94,0,0,98,0,0,0,0,0,0,0,0,0
    },
    { 35,99,0,37,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,38,0,0,0,0
     ,40,0,0,41,0,0,33,0,0,0,0,0,0,100,39,0,0,0,34,0,0,0,31,36,0
     ,0
    },
    { 35,101,0,37,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32,38,0,0,0,0
     ,40,0,0,41,0,0,33,0,0,0,0,0,0,102,39,0,0,0,34,0,0,0,31,36,0
     ,0
    },
    { 107,14,0,109,0,0,0,0,104,113,0,0,0,0,0,0,0,0,0,0,0,0,110,0,0
     ,0,0,111,0,0,112,0,0,0,0,0,0,0,0,0,103,0,0,0,0,106,0,0,0,105
     ,108,0,0
    },
    { 0,115,0,0,0,0,0,0,0,120,0,0,0,0,0,0,114,0,0,0,0,118,0,0,0,0
     ,0,0,0,0,0,0,0,119,0,0,0,0,0,0,116,0,0,121,0,0,0,0,0,117,0,0
     ,0
    },
    { 35,122,0,37,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,124,38,0,0,0
     ,0,40,0,0,41,0,0,125,0,0,0,0,0,0,123,39,0,0,0,34,0,0,0,31,36
     ,0,0
    },
    { 130,14,0,132,0,0,0,0,127,0,0,0,0,0,0,0,0,0,0,0,0,0,133,0,0,0
     ,0,0,0,0,135,0,0,0,0,0,0,0,0,0,126,134,0,0,0,129,0,0,0,128
     ,131,0,0
    },
    { 0,6,0,0,136,0,0,0,0,138,0,0,0,0,0,140,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,139,0,0,0,0,0,137,137,0,0,137,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,141,0,0,142,0,0,0,0,138,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,144,0,0,0,0,0,0,0,0,143,143,0,0,143,0,0,0,0,0,0,0,0,0,0,0,0
     ,0
    },
    { 0,14,0,0,0,0,0,0,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,145,0,0,0,0,0,0,0,0,147,0,0,0
    },
    { 0,141,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,148,148,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,9,0,0,0,0,0,0,0,149,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
     ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    },
    { 0,0,0,0,0,0,156,152,0,0,0,0,0,0,0,0,154,0,152,155,0,0,0,158
     ,152,0,0,0,0,0,0,0,151,0,0,0,152,150,157,0,0,0,0,0,0,0,153,0
     ,1,0,0,0,0
    }
};

static word _LR_offset [] =
{
    0,
    0,
    1,
    3,
    7,
    14,
    19,
    24,
    29,
    31,
    34,
    37,
    40,
    47,
    53,
    57,
    62,
    65,
    68,
    74,
    80,
    86,
    92,
    98,
    104,
    110,
    115,
    120,
    125,
    130,
    136,
    140,
    143,
    148,
    153,
    160,
    167,
    174,
    181,
    188,
    195,
    202,
    209,
    213,
    219,
    224,
    227,
    230,
    235,
    238,
    241,
    247,
    253,
    259,
    265,
    271,
    277,
    283,
    288,
    293,
    297,
    303,
    308,
    311,
    314,
    320,
    326,
    332,
    338,
    344,
    350,
    356,
    361,
    366,
    371,
    373,
    377,
    382,
    387,
    392,
    395,
    398,
    401,
    405,
    409,
    412,
    417,
    421,
    424,
    427,
    431,
    435,
    439,
    441,
    446,
    451,
    454,
    457,
    462,
    466,
    470,
    476,
    480,
    486,
    491,
    494,
    497,
    503,
    509,
    515,
    521,
    527,
    533,
    539,
    544,
    546,
    551,
    557,
    560,
    564,
    568,
    574,
    578,
    582,
    587,
    591,
    595,
    600,
    603,
    606,
    612,
    618,
    624,
    630,
    636,
    642,
    648,
    652,
    655,
    662,
    666,
    670,
    674,
    678,
    681,
    685,
    691,
    694,
    697,
    700,
    705,
    708,
    711,
    714,
    717,
    719,
    722,
    727,
    730
};

static word _LR_vector [] =
{
    _LR_STOP,
    0,_LR_STOP,
    1,2,3,_LR_STOP,
    4,5,6,7,3,8,_LR_STOP,
    9,10,3,8,_LR_STOP,
    11,1,2,3,_LR_STOP,
    12,13,3,8,_LR_STOP,
    14,_LR_STOP,
    15,16,_LR_STOP,
    10,3,_LR_STOP,
    17,3,_LR_STOP,
    18,5,6,7,3,8,_LR_STOP,
    5,6,7,3,8,_LR_STOP,
    19,15,16,_LR_STOP,
    20,21,15,16,_LR_STOP,
    22,3,_LR_STOP,
    7,3,_LR_STOP,
    20,15,23,24,3,_LR_STOP,
    20,15,25,24,3,_LR_STOP,
    20,15,26,27,3,_LR_STOP,
    20,15,28,29,3,_LR_STOP,
    20,15,30,31,3,_LR_STOP,
    20,15,32,33,3,_LR_STOP,
    20,15,34,24,3,_LR_STOP,
    20,35,36,3,_LR_STOP,
    20,37,24,3,_LR_STOP,
    20,38,24,3,_LR_STOP,
    20,39,40,3,_LR_STOP,
    41,42,21,15,16,_LR_STOP,
    43,40,3,_LR_STOP,
    24,3,_LR_STOP,
    41,42,24,3,_LR_STOP,
    41,42,44,3,_LR_STOP,
    41,42,15,6,7,3,_LR_STOP,
    41,42,15,23,24,3,_LR_STOP,
    41,42,15,25,24,3,_LR_STOP,
    41,42,15,26,27,3,_LR_STOP,
    41,42,15,28,29,3,_LR_STOP,
    41,42,15,30,31,3,_LR_STOP,
    41,42,15,32,33,3,_LR_STOP,
    41,42,15,34,24,3,_LR_STOP,
    15,7,3,_LR_STOP,
    41,42,15,7,3,_LR_STOP,
    45,15,7,3,_LR_STOP,
    46,3,_LR_STOP,
    36,3,_LR_STOP,
    47,21,15,16,_LR_STOP,
    48,3,_LR_STOP,
    27,3,_LR_STOP,
    47,15,6,7,3,_LR_STOP,
    47,15,23,24,3,_LR_STOP,
    47,15,25,24,3,_LR_STOP,
    47,15,28,29,3,_LR_STOP,
    47,15,30,31,3,_LR_STOP,
    47,15,32,33,3,_LR_STOP,
    47,15,34,24,3,_LR_STOP,
    47,49,24,3,_LR_STOP,
    47,50,24,3,_LR_STOP,
    15,27,3,_LR_STOP,
    41,42,15,27,3,_LR_STOP,
    51,21,15,16,_LR_STOP,
    52,3,_LR_STOP,
    29,3,_LR_STOP,
    51,15,6,7,3,_LR_STOP,
    51,15,23,24,3,_LR_STOP,
    51,15,25,24,3,_LR_STOP,
    51,15,26,27,3,_LR_STOP,
    51,15,30,31,3,_LR_STOP,
    51,15,32,33,3,_LR_STOP,
    51,15,34,24,3,_LR_STOP,
    51,53,54,3,_LR_STOP,
    51,55,56,3,_LR_STOP,
    51,57,24,3,_LR_STOP,
    58,_LR_STOP,
    59,60,3,_LR_STOP,
    61,15,29,3,_LR_STOP,
    62,15,29,3,_LR_STOP,
    61,53,54,3,_LR_STOP,
    54,3,_LR_STOP,
    63,3,_LR_STOP,
    64,3,_LR_STOP,
    59,65,3,_LR_STOP,
    15,54,3,_LR_STOP,
    60,3,_LR_STOP,
    66,15,54,3,_LR_STOP,
    67,68,3,_LR_STOP,
    69,3,_LR_STOP,
    65,3,_LR_STOP,
    66,68,3,_LR_STOP,
    70,40,3,_LR_STOP,
    66,71,3,_LR_STOP,
    72,_LR_STOP,
    73,15,29,3,_LR_STOP,
    74,15,29,3,_LR_STOP,
    56,3,_LR_STOP,
    75,3,_LR_STOP,
    76,77,24,3,_LR_STOP,
    77,24,3,_LR_STOP,
    15,78,3,_LR_STOP,
    41,79,15,78,3,_LR_STOP,
    15,29,3,_LR_STOP,
    41,42,15,29,3,_LR_STOP,
    80,21,15,16,_LR_STOP,
    81,3,_LR_STOP,
    31,3,_LR_STOP,
    80,15,6,7,3,_LR_STOP,
    80,15,23,24,3,_LR_STOP,
    80,15,25,24,3,_LR_STOP,
    80,15,26,27,3,_LR_STOP,
    80,15,28,29,3,_LR_STOP,
    80,15,32,33,3,_LR_STOP,
    80,15,34,24,3,_LR_STOP,
    80,82,83,3,_LR_STOP,
    84,_LR_STOP,
    61,15,31,3,_LR_STOP,
    85,62,15,31,3,_LR_STOP,
    83,3,_LR_STOP,
    85,83,3,_LR_STOP,
    85,86,3,_LR_STOP,
    85,87,88,24,3,_LR_STOP,
    88,24,3,_LR_STOP,
    15,89,3,_LR_STOP,
    90,15,89,3,_LR_STOP,
    42,24,3,_LR_STOP,
    42,44,3,_LR_STOP,
    91,21,15,16,_LR_STOP,
    92,3,_LR_STOP,
    33,3,_LR_STOP,
    91,15,6,7,3,_LR_STOP,
    91,15,23,24,3,_LR_STOP,
    91,15,25,24,3,_LR_STOP,
    91,15,26,27,3,_LR_STOP,
    91,15,28,29,3,_LR_STOP,
    91,15,30,31,3,_LR_STOP,
    91,15,34,24,3,_LR_STOP,
    93,94,3,_LR_STOP,
    94,3,_LR_STOP,
    4,5,95,96,3,8,_LR_STOP,
    97,98,3,_LR_STOP,
    99,100,3,_LR_STOP,
    15,94,3,_LR_STOP,
    101,98,3,_LR_STOP,
    98,3,_LR_STOP,
    102,98,3,_LR_STOP,
    103,21,104,15,16,_LR_STOP,
    105,3,_LR_STOP,
    96,3,_LR_STOP,
    100,3,_LR_STOP,
    106,107,15,16,_LR_STOP,
    108,3,_LR_STOP,
    11,0,_LR_STOP,
    40,3,_LR_STOP,
    11,109,_LR_STOP,
    110,_LR_STOP,
    11,111,_LR_STOP,
    11,112,94,3,_LR_STOP,
    113,3,_LR_STOP,
    114,3,_LR_STOP
};

static HOOK *_LR_module [115] = {
    determine_initial_screen,
    open_main_admin_menu,
    show_main_admin_menu,
    decode_http_request_reponse,
    use_defaults_config_name,
    load_current_config_file,
    open_config_server,
    show_config_server,
    dialog_call,
    open_config_list,
    show_config_list_first,
    close_all_forms,
    open_vhost_wizard,
    show_vhost_wizard,
    check_config_list_livelink,
    close_current_form,
    dialog_return,
    show_config_list_next,
    use_basehost_config_name,
    cancel_current_config_file,
    update_config_server,
    save_current_config_file,
    show_config_server_defaults,
    open_config_aliases,
    show_config_value_list_first,
    open_config_vhosts,
    open_config_cgi,
    show_config_cgi,
    open_config_ftp,
    show_config_ftp,
    open_config_security,
    show_config_security,
    open_config_logging,
    show_config_logging,
    open_config_mimes,
    open_config_errors,
    show_config_errors,
    open_config_wsx,
    open_config_filter,
    test_url_mapping,
    reshow_current_form,
    validate_config_value_list,
    update_config_value_list,
    clear_config_value_list,
    show_config_value_list_next,
    update_config_errors,
    show_config_errors_defaults,
    update_config_cgi,
    show_config_cgi_defaults,
    open_config_cgi_envir,
    open_config_cgi_alias,
    update_config_ftp,
    show_config_ftp_defaults,
    open_config_ftp_users,
    show_config_ftp_users_first,
    open_config_ftp_dirs,
    show_config_ftp_dirs_first,
    open_config_ftp_alias,
    check_ftp_users_livelink,
    open_config_ftp_user,
    show_config_ftp_user_new,
    cancel_config_resource_file,
    save_config_resource_file,
    show_config_ftp_users_next,
    show_config_ftp_users_same,
    show_config_ftp_user,
    update_config_ftp_user,
    delete_config_ftp_user,
    show_config_ftp_user_first,
    show_config_ftp_user_defaults,
    set_permissions_as_chosen,
    show_config_ftp_user_next,
    check_ftp_dir_livelink,
    cancel_config_ftp_dir_file,
    save_config_ftp_dir_file,
    show_config_ftp_dirs_next,
    check_new_ftp_dir_name,
    open_config_ftp_user_list,
    show_config_ftp_dirs_same,
    update_config_ftp_user_list,
    update_config_security,
    show_config_security_defaults,
    open_config_resources,
    show_config_resources_first,
    check_resources_livelink,
    update_config_resources,
    show_config_resources_next,
    check_new_resource_name,
    open_config_user_list,
    show_config_resources_same,
    update_config_user_list,
    update_config_logging,
    show_config_logging_defaults,
    clear_console_panel_statistics,
    show_console_panel,
    open_console_config,
    show_console_config,
    open_console_messages,
    show_console_messages,
    open_connection_list,
    show_connection_list,
    clear_console_messages,
    invert_console_data,
    update_console_config,
    reload_server_base_config,
    show_console_config_defaults,
    validate_vhost_definition,
    create_vhost_definition,
    send_resource_file_if_known,
    terminate_the_thread,
    check_simple_livelink,
    redirect_to_home_page,
    open_console_panel,
    restart_http_server_agent,
    shutdown_http_server_agent
};

#if (defined (DEBUG))
static char *_LR_mname [115] =
{
     "Determine-Initial-Screen",
     "Open-Main-Admin-Menu",
     "Show-Main-Admin-Menu",
     "Decode-Http-Request-Reponse",
     "Use-Defaults-Config-Name",
     "Load-Current-Config-File",
     "Open-Config-Server",
     "Show-Config-Server",
     "Dialog-Call",
     "Open-Config-List",
     "Show-Config-List-First",
     "Close-All-Forms",
     "Open-Vhost-Wizard",
     "Show-Vhost-Wizard",
     "Check-Config-List-Livelink",
     "Close-Current-Form",
     "Dialog-Return",
     "Show-Config-List-Next",
     "Use-Basehost-Config-Name",
     "Cancel-Current-Config-File",
     "Update-Config-Server",
     "Save-Current-Config-File",
     "Show-Config-Server-Defaults",
     "Open-Config-Aliases",
     "Show-Config-Value-List-First",
     "Open-Config-Vhosts",
     "Open-Config-Cgi",
     "Show-Config-Cgi",
     "Open-Config-Ftp",
     "Show-Config-Ftp",
     "Open-Config-Security",
     "Show-Config-Security",
     "Open-Config-Logging",
     "Show-Config-Logging",
     "Open-Config-Mimes",
     "Open-Config-Errors",
     "Show-Config-Errors",
     "Open-Config-Wsx",
     "Open-Config-Filter",
     "Test-Url-Mapping",
     "Reshow-Current-Form",
     "Validate-Config-Value-List",
     "Update-Config-Value-List",
     "Clear-Config-Value-List",
     "Show-Config-Value-List-Next",
     "Update-Config-Errors",
     "Show-Config-Errors-Defaults",
     "Update-Config-Cgi",
     "Show-Config-Cgi-Defaults",
     "Open-Config-Cgi-Envir",
     "Open-Config-Cgi-Alias",
     "Update-Config-Ftp",
     "Show-Config-Ftp-Defaults",
     "Open-Config-Ftp-Users",
     "Show-Config-Ftp-Users-First",
     "Open-Config-Ftp-Dirs",
     "Show-Config-Ftp-Dirs-First",
     "Open-Config-Ftp-Alias",
     "Check-Ftp-Users-Livelink",
     "Open-Config-Ftp-User",
     "Show-Config-Ftp-User-New",
     "Cancel-Config-Resource-File",
     "Save-Config-Resource-File",
     "Show-Config-Ftp-Users-Next",
     "Show-Config-Ftp-Users-Same",
     "Show-Config-Ftp-User",
     "Update-Config-Ftp-User",
     "Delete-Config-Ftp-User",
     "Show-Config-Ftp-User-First",
     "Show-Config-Ftp-User-Defaults",
     "Set-Permissions-As-Chosen",
     "Show-Config-Ftp-User-Next",
     "Check-Ftp-Dir-Livelink",
     "Cancel-Config-Ftp-Dir-File",
     "Save-Config-Ftp-Dir-File",
     "Show-Config-Ftp-Dirs-Next",
     "Check-New-Ftp-Dir-Name",
     "Open-Config-Ftp-User-List",
     "Show-Config-Ftp-Dirs-Same",
     "Update-Config-Ftp-User-List",
     "Update-Config-Security",
     "Show-Config-Security-Defaults",
     "Open-Config-Resources",
     "Show-Config-Resources-First",
     "Check-Resources-Livelink",
     "Update-Config-Resources",
     "Show-Config-Resources-Next",
     "Check-New-Resource-Name",
     "Open-Config-User-List",
     "Show-Config-Resources-Same",
     "Update-Config-User-List",
     "Update-Config-Logging",
     "Show-Config-Logging-Defaults",
     "Clear-Console-Panel-Statistics",
     "Show-Console-Panel",
     "Open-Console-Config",
     "Show-Console-Config",
     "Open-Console-Messages",
     "Show-Console-Messages",
     "Open-Connection-List",
     "Show-Connection-List",
     "Clear-Console-Messages",
     "Invert-Console-Data",
     "Update-Console-Config",
     "Reload-Server-Base-Config",
     "Show-Console-Config-Defaults",
     "Validate-Vhost-Definition",
     "Create-Vhost-Definition",
     "Send-Resource-File-If-Known",
     "Terminate-The-Thread",
     "Check-Simple-Livelink",
     "Redirect-To-Home-Page",
     "Open-Console-Panel",
     "Restart-Http-Server-Agent",
     "Shutdown-Http-Server-Agent"
};

static char *_LR_sname [27] =
{
     "After-Init",
     "Start-Session",
     "Select-Initial",
     "Main-Menu",
     "Config-List",
     "Config-Server",
     "Config-Value-List",
     "Config-Server-List",
     "Config-Errors",
     "Config-Cgi",
     "Config-Cgi-Sub-List",
     "Config-Ftp",
     "Config-Ftp-Users",
     "Config-Ftp-User",
     "Config-Ftp-Dirs",
     "Config-Ftp-User-List",
     "Config-Ftp-Sub-List",
     "Config-Security",
     "Config-Resources",
     "Config-User-List",
     "Config-Logging",
     "Console-Panel",
     "Console-Messages",
     "Console-Config",
     "Connection-List",
     "Vhost-Wizard",
     "Defaults"
};

static char *_LR_ename [53] =
{
     "Aliases-Event",
     "Back-Event",
     "Basehost-Event",
     "Cgi-Event",
     "Clear-Event",
     "Config-Event",
     "Console-Event",
     "Data-Error-Event",
     "Default-Event",
     "Define-Event",
     "Define-Aliases-Event",
     "Define-Dirs-Event",
     "Define-Environ-Event",
     "Define-Users-Event",
     "Delete-Event",
     "Details-Event",
     "Enter-Event",
     "Errors-Event",
     "Exception-Event",
     "Exit-Event",
     "Filters-Event",
     "First-Event",
     "Ftp-Event",
     "Halt-Event",
     "Help-Event",
     "Hosts-Event",
     "Invert-Event",
     "Logging-Event",
     "Main-Event",
     "Messages-Event",
     "Mimes-Event",
     "New-Event",
     "New-Session-Event",
     "Next-Event",
     "Ok-Event",
     "Refresh-Event",
     "Reshow-Form-Event",
     "Resource-Event",
     "Restart-Event",
     "Return-Event",
     "Save-Event",
     "Security-Event",
     "Select-Config-Event",
     "Select-Resource-Event",
     "Select-User-Event",
     "Server-Event",
     "Shutdown-Event",
     "Test-Event",
     "Timeout-Event",
     "Undo-Event",
     "Vhosts-Event",
     "Wizard-Event",
     "Wsx-Event"
};
#else
static char *_LR_mname [115] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33",
     "34",
     "35",
     "36",
     "37",
     "38",
     "39",
     "40",
     "41",
     "42",
     "43",
     "44",
     "45",
     "46",
     "47",
     "48",
     "49",
     "50",
     "51",
     "52",
     "53",
     "54",
     "55",
     "56",
     "57",
     "58",
     "59",
     "60",
     "61",
     "62",
     "63",
     "64",
     "65",
     "66",
     "67",
     "68",
     "69",
     "70",
     "71",
     "72",
     "73",
     "74",
     "75",
     "76",
     "77",
     "78",
     "79",
     "80",
     "81",
     "82",
     "83",
     "84",
     "85",
     "86",
     "87",
     "88",
     "89",
     "90",
     "91",
     "92",
     "93",
     "94",
     "95",
     "96",
     "97",
     "98",
     "99",
     "100",
     "101",
     "102",
     "103",
     "104",
     "105",
     "106",
     "107",
     "108",
     "109",
     "110",
     "111",
     "112",
     "113",
     "114"
};

static char *_LR_sname [27] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26"
};

static char *_LR_ename [53] =
{
     "0",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16",
     "17",
     "18",
     "19",
     "20",
     "21",
     "22",
     "23",
     "24",
     "25",
     "26",
     "27",
     "28",
     "29",
     "30",
     "31",
     "32",
     "33",
     "34",
     "35",
     "36",
     "37",
     "38",
     "39",
     "40",
     "41",
     "42",
     "43",
     "44",
     "45",
     "46",
     "47",
     "48",
     "49",
     "50",
     "51",
     "52"
};
#endif

MODULE dialog_call (THREAD *thread)
{
    if (thread-> LR_stack_size < 20)
        thread-> LR_stack [thread-> LR_stack_size++] = thread-> LR_state;
    else
      {
        fprintf (stdout,
            "State %d - Dialog-Call overflow\n", thread-> LR_state);
        exit (EXIT_FAILURE);
      }
}

MODULE dialog_return (THREAD *thread)
{
    if (thread-> LR_stack_size > 0)
      {
        thread-> LR_state = thread-> LR_stack [--(thread-> LR_stack_size)];
        raise_exception (return_event);
      }
    else
      {
        fprintf (stdout,
            "State %d - Dialog-Return underflow\n", thread-> LR_state);
        exit (EXIT_FAILURE);
      }
}
